LPD-23926 Apply the new configuration to allow or prevent the inclusion of the parent sites in the notification recipient, when it type is site role
liferay-workflow/liferay-portal pull request #1134
Opened 2024-04-25 15:54 UTC by p-albuquerque

Related issue: https://issues.liferay.com/browse/LPD-23926

2024-04-25 15:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5423/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5423/jenkins-report.html">here</a>.</b></p>

2024-04-25 15:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p-albuquerque/liferay-portal/tree/LPD-23926_final">LPD-23926_final</a><br/>Branch GIT ID: <a href="https://github.com/p-albuquerque/liferay-portal/commit/a61b4052b0c40aa2c469b5bf12b89ce1119324c8">a61b4052b0c40aa2c469b5bf12b89ce1119324c8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5423/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5423/jenkins-report.html">here</a>.</h5></details></html>

2024-04-25 16:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5423/">test-portal-source-format#5423</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5423/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563632969">[master] ci:test:sf - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-25[08:55:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563632969<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/21394/">publish-testray-report#21394</a><br/></div></div>

2024-04-25 16:35 UTC, p-albuquerque commented
Depends on: https://github.com/brianchandotcom/liferay-portal/pull/149628

2024-04-29 12:43 UTC, MarinhoFeliphe requested changes
Hey @linolaoj I've reviewed this pull request, @p-albuquerque please see my comments.

Thanks!

2024-04-29 13:22 UTC, p-albuquerque commented on modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/notification/recipient/ScriptNotificationRecipientBuilder.java
> +		BundleContext bundleContext, Map<String, Object> properties) {
Hi @MarinhoFeliphe  If I remove `Map<String, Object> properties` parameter here, I'm forced to remove the `@Override`, so it means that [ScriptNotificationRecipientBuilder.java](https://github.com/liferay-workflow/liferay-portal/pull/1134/files/24ac3e4619271edafddf895ef3fcaa99db3c1854#diff-b6a07d9633d7c0900201d182e6d3b9c2815cb8614e1c1f9364761c852e2480a3) will contains two activate methods. It's okay keep this way?

2024-04-29 13:24 UTC, p-albuquerque commented on modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/notification/recipient/RoleNotificationRecipientBuilder.java
> +			WorkflowDefinitionConfiguration.class, properties);
Hi @MarinhoFeliphe even without the `@Modified` annotation, it have been worked. I change the configuration several times and I was faced no issues. But I will try it with this annotation as well

2024-04-29 13:28 UTC, p-albuquerque commented on modules/apps/portal-workflow/portal-workflow-kaleo-test/src/testIntegration/java/com/liferay/portal/workflow/kaleo/internal/runtime/integration/test/WorkflowTaskManagerImplTest.java
> +		article = _journalArticleLocalService.getArticle(article.getId());
Hi @MarinhoFeliphe I will put them in another test method, then I was thinking about use another asset to test it like `BlogsEntry`. What do you think?

2024-04-29 14:34 UTC, p-albuquerque commented on modules/apps/portal-workflow/portal-workflow-kaleo-test/src/testIntegration/java/com/liferay/portal/workflow/kaleo/internal/runtime/integration/test/WorkflowTaskManagerImplTest.java
> +				"preventNotifyingAncestorSites", false
I was removed it and tested again. Everything works well! 
Thanks

2024-04-29 15:18 UTC, p-albuquerque commented
ci:test:sf

2024-04-29 16:45 UTC, p-albuquerque commented
ci:test:sf

2024-04-29 16:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/6230/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6230/jenkins-report.html">here</a>.</b></p>

2024-04-29 16:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c77921f49014810656a536569de9f1d02704bca7">c77921f49014810656a536569de9f1d02704bca7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p-albuquerque/liferay-portal/tree/LPD-23926_final">LPD-23926_final</a><br/>Branch GIT ID: <a href="https://github.com/p-albuquerque/liferay-portal/commit/cd9a1d1b747d92c55a18a2384a74f60004eda4b5">cd9a1d1b747d92c55a18a2384a74f60004eda4b5</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6230/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6230/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/portal.properties expected:&lt;...NUS__NUMBER2__NUMBER[0__NUMBER2__NUMBER1__NUMBER3_
     [java]     #
     [java]     feature.flag.LPD-20213=false
     [java] 
     [java]     #
     [java]     # Env: LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEL__UPPERCASEP__UPPERCASED__MINUS__NUMBER2__NUMBER3__NUMBER2__NUMBER1__NUMBER0_
     [java]     #
     [java]     feature.flag.LPD-23210]=false
     [java] 
     [java]     #
     [java]     # ...&gt; but was:&lt;...NUS__NUMBER2__NUMBER[3__NUMBER2__NUMBER1__NUMBER0_
     [java]     #
     [java]     feature.flag.LPD-23210=false
     [java] 
     [java]     #
     [java]     # Env: LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEL__UPPERCASEP__UPPERCASED__MINUS__NUMBER2__NUMBER0__NUMBER2__NUMBER1__NUMBER3_
     [java]     #
     [java]     feature.flag.LPD-20213]=false
     [java] 
     [java]     #
     [java]     # ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:59.048 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-5/job/test-portal-source-format/6230//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240429094936648.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240429094936648.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1467798304.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null323543355</pre></details></html>

2024-04-29 16:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6230/">test-portal-source-format#6230</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6230/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564316485">[master] ci:test:sf - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-29[09:45:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564316485<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/2940/">publish-testray-report#2940</a><br/></div></div>

2024-04-29 20:34 UTC, p-albuquerque commented
ci:test:sf

2024-04-29 20:34 UTC, p-albuquerque commented
ci:test:relevant

2024-04-29 20:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13234/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13234/jenkins-report.html">here</a>.</b></p>

2024-04-29 20:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7130/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7130/jenkins-report.html">here</a>.</b></p>

2024-04-29 20:44 UTC, MarinhoFeliphe approved these changes
LGTM!! :tada:

2024-04-29 20:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7130/">test-portal-source-format#7130</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7130/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564365256">[master] ci:test:sf - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-29[13:37:14]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564365256<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/4759/">publish-testray-report#4759</a><br/></div></div>

2024-04-29 23:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 143 out of 165 jobs passed in 3 hours 23 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/514">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1267401_13234</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c77921f49014810656a536569de9f1d02704bca7">c77921f49014810656a536569de9f1d02704bca7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564340664">EE Development Acceptance (master) - 512 - 2024-04-29[08:38:24]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 143 out of 165 jobs PASSED</strong></summary><div><h4>22 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13234/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418352/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973221/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928102/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928103/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943112/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928091/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999026/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989017/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092061/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389640/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904995/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326022/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943116/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943117/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866378/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884235/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928099/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866380/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943120/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866379/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943119/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326019/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332581/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866389/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090152/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866388/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/904999/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812533/"><strike>modules-integration-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090149/">modules-integration-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973219/">modules-integration-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866384/">modules-integration-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928105/">modules-integration-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884240/">modules-integration-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928100/">modules-integration-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884236/">modules-integration-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866381/">modules-integration-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989023/">modules-integration-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973216/">modules-integration-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-3 [...]

2024-04-30 00:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13234/">test-portal-acceptance-pullrequest(master)#13234</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13234/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564411813">[master] ci:test:relevant - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-29[13:35:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564411813<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/30814/">publish-testray-report#30814</a><br/></div></div>

2024-04-30 12:03 UTC, p-albuquerque commented
ci:test:workflow

2024-04-30 12:04 UTC, p-albuquerque commented
ci:test:workflow-metrics

2024-04-30 12:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>workflow</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13246/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13246/jenkins-report.html">here</a>.</b></p>

2024-04-30 12:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>workflow-metrics</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4265/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4265/jenkins-report.html">here</a>.</b></p>

2024-04-30 14:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:workflow-metrics - 108 out of 118 jobs passed in 2 hours 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564460465">EE Development Acceptance (master) - 514 - 2024-04-29[16:38:09]</a></p><details><summary><strong>ci:test:workflow-metrics - 108 out of 118 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4265/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418696/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865600/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092405/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389992/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092406/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381175/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581430/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326251/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581431/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389993/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865601/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389983/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389984/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326244/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389985/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092395/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326245/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315323/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418692/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332896/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418693/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332900/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332901/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422275/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381180/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422277/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092397/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326246/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389988/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326247/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092398/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389987/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326248/"><strike>functional-tomcat90-mysql57-jdk8/1/6</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389989/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092400/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092399/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870292/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381178/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315321/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581434/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092411/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389996/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581435/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstrea [...]

2024-04-30 14:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4265/">test-portal-acceptance-pullrequest(master)#4265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>workflow-metrics<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564537954">[master] ci:test:workflow-metrics - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-30[05:23:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564537954<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32243/">publish-testray-report#32243</a><br/></div></div>

2024-04-30 15:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:workflow - 280 out of 297 jobs passed in 2 hours 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564460465">EE Development Acceptance (master) - 514 - 2024-04-29[16:38:09]</a></p><details><summary><strong>ci:test:workflow - 280 out of 297 jobs PASSED</strong></summary><div><h4>17 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13246/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374901/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418723/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422295/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390011/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332926/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315345/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374895/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381186/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422296/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332927/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381187/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418714/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943510/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581457/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905332/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999444/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315340/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884323/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418729/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390016/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999451/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315352/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381192/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870306/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092433/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999452/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418715/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943511/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418716/"><strike>functional-tomcat90-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943512/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905334/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870303/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374891/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418719/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374890/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418717/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315350/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374898/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381190/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581459/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905337/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092429/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326267/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/382516/">functional-tomcat90-mysql57-jdk8/1/ [...]

2024-04-30 15:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13246/">test-portal-acceptance-pullrequest(master)#13246</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13246/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>workflow<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/1134">liferay-workflow#1134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564540094">[master] ci:test:workflow - p-albuquerque &gt; liferay-workflow - PR#1134 - 2024-04-30[05:20:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564540094<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/30830/">publish-testray-report#30830</a><br/></div></div>

2024-04-30 17:14 UTC, closed without merging

2024-04-30 17:14 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/149819
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/1278//consoleFull)