LPS-127391 Hidden controls for detail view
liferay-workflow/liferay-portal pull request #278
Opened 2021-03-17 14:38 UTC by jotascript

2021-03-17 14:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-03-17 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/204/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/204/jenkins-report.html">here</a>.</b></p>

2021-03-17 14:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/231/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/231/jenkins-report.html">here</a>.</b></p>

2021-03-17 14:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cf1bfb038cd72870018de6b9f37c082b71e4519">8cf1bfb038cd72870018de6b9f37c082b71e4519</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jotascript/liferay-portal/tree/LPS-127391">LPS-127391</a><br/>Branch GIT ID: <a href="https://github.com/jotascript/liferay-portal/commit/b97f10f0371eb55ff3cb3f9bc902dee615bf02c7">b97f10f0371eb55ff3cb3f9bc902dee615bf02c7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/204/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/204/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Use StringUtil.replaceFirst(String, char, char) or StringUtil.replaceFirst(String, char, String) instead, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/string_methods_check.markdown: ./modules/apps/app-builder/app-builder-service/src/main/java/com/liferay/app/builder/internal/workflow/AppBuilderAppWorkflowHandler.java 116 (SourceCheck:StringMethodsCheck)
     [java] 2: Do not use type 'ServiceContext' in API method signature, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/java_api_signature_check.markdown: ./portal-kernel/src/com/liferay/portal/kernel/workflow/WorkflowHandler.java (SourceCheck:JavaAPISignatureCheck)
     [java] 3: ./modules/apps/app-builder/app-builder-service/src/main/java/com/liferay/app/builder/internal/workflow/AppBuilderAppWorkflowHandler.java expected:&lt;...otificationRedirect([
     [java] 				workflowTaskId, serviceContext);
     [java] 		\}
     [java] 
     [java] 		try \{
     [java] 			PortletURL portletURL = PortletURLFactoryUtil.create(
     [java] 				serviceContext.getRequest(),
     [java] 				GetterUtil.getString(serviceContext.getAttribute("portletId")),
     [java] 				GetterUtil.getLong(serviceContext.getAttribute("plid")),
     [java] 				PortletRequest.RENDER_PHASE);
     [java] 
     [java] 			portletURL.setParameter("mvcPath", "/view_app_entries.jsp");
     [java] 			portletURL.setWindowState(WindowState.MAXIMIZED);
     [java] 
     [java] 			return StringUtil.replaceFirst(
     [java] 				portletURL.toString(), "?",
     [java] 				]"#/view-entry/" + dd...&gt; but was:&lt;...otificationRedirect([workflowTaskId, serviceContext);
     [java] 		\}
     [java] 
     [java] 		try \{
     [java] 			PortletURL portletURL = PortletURLFactoryUtil.create(
     [java] 				serviceContext.getRequest(),
     [java] 				GetterUtil.getString(serviceContext.getAttribute("portletId")),
     [java] 				GetterUtil.getLong(serviceContext.getAttribute("plid")),
     [java] 				PortletRequest.RENDER_PHASE);
     [java] 
     [java] 			portletURL.setParameter("mvcPath", "/view_app_entries.jsp");
     [java] 			portletURL.setWindowState(WindowState.MAXIMIZED);
     [java] 
     [java] 			return StringUtil.replaceFirst(portletURL.toString(),
     [java] 				"?", ]"#/view-entry/" + dd...&gt;
     [java] </code></pre></details></html>

2021-03-17 14:46 UTC, naraandrade commented
ci:stop

2021-03-17 14:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cf1bfb038cd72870018de6b9f37c082b71e4519">8cf1bfb038cd72870018de6b9f37c082b71e4519</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cf1bfb038cd72870018de6b9f37c082b71e4519">8cf1bfb038cd72870018de6b9f37c082b71e4519</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1647">Acceptance Upstream DXP (master) #1647</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/231/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/231/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/231/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>Build was aborted</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-03-17 15:09 UTC, rafaprax requested changes

2021-03-17 15:09 UTC, rafaprax commented on modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/pages/entry/ViewEntryUpperToolbar.es.js
>  	dataRecordId,
Hey @jotascript, please rename this to `showNavigationControls` or something like this.

Thx

2021-03-17 15:23 UTC, MarinhoFeliphe commented on portal-kernel/src/com/liferay/portal/kernel/workflow/packageinfo
> +version 10.0.0
Ok

2021-03-17 16:56 UTC, MarinhoFeliphe commented
Just started reviewing :)

2021-03-18 14:04 UTC, MarinhoFeliphe commented
resent here [#279](https://github.com/liferay-workflow/liferay-portal/pull/279)

2021-03-18 14:04 UTC, closed without merging