LPS-131420 Fix test
liferay-workflow/liferay-portal pull request #339
Opened 2021-05-04 13:47 UTC by jotascript

2021-05-04 13:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-04 13:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/4773/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/4773/jenkins-report.html">here</a>.</b></p>

2021-05-04 13:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a31589a97b13d747dcc409156d4e67907ead0bfd">a31589a97b13d747dcc409156d4e67907ead0bfd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jotascript/liferay-portal/tree/LPS-131420">LPS-131420</a><br/>Branch GIT ID: <a href="https://github.com/jotascript/liferay-portal/commit/ae59eb700040378622455338734c72cb4893223b">ae59eb700040378622455338734c72cb4893223b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4773/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4773/jenkins-report.html">here</a>.</h5></details></html>

2021-05-04 13:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4773/">test-portal-source-format#4773</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4773/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/339">liferay-workflow#339</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530207580">[master] ci:test:sf - jotascript &gt; liferay-workflow - PR#339 - 2021-05-04[06:48:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/980/">publish-testray-report#980</a><br/></div></div>

2021-05-05 12:36 UTC, rafaprax requested changes

2021-05-05 12:36 UTC, rafaprax commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/instance-list-page/InstanceListPageTable.es.js
> +						<ListHeadItem
Hey @jotascript, rename it to `dueDate` instead and apply it to other places, if any. Thx Bro

2021-05-06 12:26 UTC, rafaprax approved these changes

2021-05-06 12:28 UTC, rafaprax commented
ci:test:relevant

2021-05-06 12:28 UTC, rafaprax commented
ci:help

2021-05-06 12:28 UTC, liferay-continuous-integration commented
## Available CI commands:
#### ci:close
&nbsp;&nbsp;&nbsp;&nbsp;Close the pull request.
#### ci:forward
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request  and forward the pullrequest to `brianchandotcom` if the required test suites pass.
#### ci:merge[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Merge in the changes from the subrepo. All tests must pass before this command will successfully run. Optionally use the force flag to bypass failed tests.
#### ci:reevaluate:[buildID]
&nbsp;&nbsp;&nbsp;&nbsp;Reevaluate the pull request result from a generated build ID.
#### ci:reopen
&nbsp;&nbsp;&nbsp;&nbsp;Reopen the pull request.
#### ci:stop[:suite]
&nbsp;&nbsp;&nbsp;&nbsp;Stop all currrently running tests. Optionally specify the name of the test suite.
#### ci:test[:suite][:SHA|nocompile|norebase]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request.Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.

&nbsp;&nbsp;&nbsp;&nbsp;List of available test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accounts** - Test Accounts tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-builder** - Test App Builder tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**documents** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test drools tests only.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test frontend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test kaleo forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lpkg** - Test LPKG tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**message-boards** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oauth2** - Test OAuth 2 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**onedrive** - Test OneDrive tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**online-editing** - Test Online Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi-gauntlet** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**project-templates** - Test project-templates tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications** - Test publications tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications-environments** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**questions-acceptance** - Test headless team acceptance tests considering Questions.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**redirect** - Test Redirection tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant** - Test relevant changes only.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**reports** - Test reports tests only.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**roles** - Test Roles tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**saml** - Test SAML tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search** - Test search tests with the Elasticsearch 7 search engine.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote** - Test only search tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote-minimum** - Test search tests with the minimum compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security** - Test security tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**seo** - Test SEO tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf** - Test source formatter.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharepoint** - Test Sharepoint 2010 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharing** - Test Asset Sharing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**site-template** - Test Site Template tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**smoke** - Run smoke test with all available configurations in PortalSmoke.testcase
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**staging** - Test Staging components tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sybase** - Test functional and integration tests on Sybase database.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**system** - Test functional and integration tests for System Management (Virtual Instances, System Settings, Instance Settings)
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**tango** - Test Tango (Segmentation and Personalization) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**tango-acceptance** - Test Tango (Segmentation and Personalization) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ta [...]

2021-05-06 12:35 UTC, ramonmsp approved these changes

2021-05-06 13:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7996/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7996/jenkins-report.html">here</a>.</b></p>

2021-05-06 15:03 UTC, rafaprax commented
ci:test:workflow-metrics

2021-05-06 15:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>workflow-metrics</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/7669/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7669/jenkins-report.html">here</a>.</b></p>

2021-05-06 15:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 22 out of 24 jobs passed in 2 hours 45 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76da930fa5d546b4b782e85737378267eb31c480">76da930fa5d546b4b782e85737378267eb31c480</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76da930fa5d546b4b782e85737378267eb31c480">76da930fa5d546b4b782e85737378267eb31c480</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1837">Acceptance Upstream DXP (master) #1837</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225752/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/329205/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/433306/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335814/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225753/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470506/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/496236/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461333/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335813/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 24 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7996/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8386/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/496235/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356713/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225754/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225752/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471664/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441935/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225755/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/329205/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/433306/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470505/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471663/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335814/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461334/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461335/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225753/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/433305/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470506/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/496236/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/329206/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461333/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471662/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335813/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7996/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream resul [...]

2021-05-06 16:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7996/">test-portal-acceptance-pullrequest(master)#7996</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7996/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/339">liferay-workflow#339</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530810800">[master] ci:test:relevant - jotascript &gt; liferay-workflow - PR#339 - 2021-05-06[06:10:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/630/">publish-testray-report#630</a><br/></div></div>

2021-05-06 16:52 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:workflow-metrics - 7 out of 10 jobs passed in 1 hour 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76da930fa5d546b4b782e85737378267eb31c480">76da930fa5d546b4b782e85737378267eb31c480</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76da930fa5d546b4b782e85737378267eb31c480">76da930fa5d546b4b782e85737378267eb31c480</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1837">Acceptance Upstream DXP (master) #1837</a></p><details><summary><strong>ci:test:workflow-metrics - 7 out of 10 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/7669/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461705/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461706/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470539/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335832/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470540/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471694/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/433497/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471693/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/432344/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7669/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 76da930fa5d546b4b782e85737378267eb31c480:</strong></summary><ol><li><div><h5><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461705/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>839 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/461705//consoleText">AXIS_VARIABLE=0,label_exp=!master #461705</a><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/461705//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
No default user was found for company 41801
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
</code></pre></div></li></ol></div></li><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/461705//consoleText">AXIS_VARIABLE=1,label_exp=!master #461705</a><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/461705//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
No default user was found for company 53742
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
</code></pre></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461706/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1433 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/461706//consoleText">AXIS_VARIABLE=2,label_exp=!master #461706</a><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/461706//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_digital_signature_digital_signature_api_">com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning[/apps/digital-signature/digital-signature-api]</a><pre><code>java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.digital.signature.model                MAJOR      1.0.0      1.0.2      2.0.0      VERSION INCREASE REQUIRED
	-   class      com.liferay.digital.signature.model.DSSessionKey
		-   method     &lt;init&gt;(java.lang.String)
			-   return     void
		-   method     &lt;init&gt;(java.lang.String,long,java.lang.String)
			-   return     void
		-   method     clone()
			-   access     protected
			-   return     java.lang.Object
		-   method     equals(java.lang.Object)
			-   return     boolean
		-   method     finalize()
			-   access     protected
			-   return     void
		-   method     getAccountKey()
			-   return     java.lang.String
		-   method     getCompanyId()
			-   return     long
		-   method     getUserName()
			-   return     java.lang.String
		-    [...]

2021-05-06 16:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/7669/">test-portal-acceptance-pullrequest(master)#7669</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7669/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>workflow-metrics<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/339">liferay-workflow#339</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530826668">[master] ci:test:workflow-metrics - jotascript &gt; liferay-workflow - PR#339 - 2021-05-06[08:12:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/589/">publish-testray-report#589</a><br/></div></div>

2021-05-06 17:16 UTC, rafaprax commented
ci:forward

2021-05-06 17:16 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-06 17:16 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`

2021-05-06 17:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/462/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/462/jenkins-report.html">here</a>.</b></p>

2021-05-06 17:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4e08b7ebfb836c9e2588390025762ba59f4ff4ce">4e08b7ebfb836c9e2588390025762ba59f4ff4ce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jotascript/liferay-portal/tree/LPS-131420">LPS-131420</a><br/>Branch GIT ID: <a href="https://github.com/jotascript/liferay-portal/commit/38e62c79cdfbab9053af686052a84f9e17e5ced2">38e62c79cdfbab9053af686052a84f9e17e5ced2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/462/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/462/jenkins-report.html">here</a>.</h5></details></html>

2021-05-06 17:19 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-2.liferay.com/job/test-portal-source-format/462//consoleFull)

2021-05-06 17:19 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101487
[Console](https://test-1-2.liferay.com/job/test-portal-source-format/462//consoleFull)

2021-05-06 17:20 UTC, closed without merging

2021-05-06 17:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/462/">test-portal-source-format#462</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/462/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/339">liferay-workflow#339</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530835077">[master] ci:test:sf - jotascript &gt; liferay-workflow - PR#339 - 2021-05-06[10:16:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/752/">publish-testray-report#752</a><br/></div></div>