LPS-132726 Add scroll inside of the metrics modal
liferay-workflow/liferay-portal pull request #380
Opened 2021-05-25 17:24 UTC by MariMalta

2021-05-25 17:24 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-25 17:25 UTC, MariMalta commented
ci:test:sf

2021-05-25 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5013/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-portal-source-format/builds/5013/jenkins-report.html">here</a>.</b></p>

2021-05-25 17:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5866/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5866/jenkins-report.html">here</a>.</b></p>

2021-05-25 17:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa3c3ba2832dce331aa3ddb1530e107598a1bc51">fa3c3ba2832dce331aa3ddb1530e107598a1bc51</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/d79bc3fc1c9300fbdeb2dfa9b04bd7b2a293de01">d79bc3fc1c9300fbdeb2dfa9b04bd7b2a293de01</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5013/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5013/jenkins-report.html">here</a>.</h5></details></html>

2021-05-25 17:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa3c3ba2832dce331aa3ddb1530e107598a1bc51">fa3c3ba2832dce331aa3ddb1530e107598a1bc51</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/d79bc3fc1c9300fbdeb2dfa9b04bd7b2a293de01">d79bc3fc1c9300fbdeb2dfa9b04bd7b2a293de01</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5866/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5866/jenkins-report.html">here</a>.</h5></details></html>

2021-05-25 17:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5013/">test-portal-source-format#5013</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5013/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535290271">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-25[10:26:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/604/">publish-testray-report#604</a><br/></div></div>

2021-05-25 17:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5866/">test-portal-source-format#5866</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5866/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535291777">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-25[10:26:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/951/">publish-testray-report#951</a><br/></div></div>

2021-05-25 19:31 UTC, rafaprax commented
Hey @MariMalta and @seltong it would be nice if you add an integration test to cover this scenario. Thank you.

2021-05-25 19:37 UTC, rafaprax requested changes
Hey @MariMalta and @seltong it would be nice if you add an integration test to cover this scenario. Thank you.

2021-05-25 19:59 UTC, seltong commented
Just started reviewing :)

2021-05-25 20:01 UTC, MarinhoFeliphe requested changes

2021-05-25 20:04 UTC, MariMalta commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-impl/src/main/java/com/liferay/portal/workflow/metrics/rest/internal/resource/v1_0/InstanceResourceImpl.java
> +		topHitsAggregation.setSize(100);
Got it! I'm going to change this now! Thank you!

2021-05-25 20:09 UTC, seltong commented
Just started reviewing :)

2021-05-26 19:54 UTC, naraandrade approved these changes

2021-05-26 20:22 UTC, MarinhoFeliphe requested changes

2021-05-26 20:22 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-test/src/testIntegration/java/com/liferay/portal/workflow/metrics/rest/resource/v1_0/test/InstanceResourceTest.java
> +				_toSLAResult(true, SLAResult.Status.NEW)
Hi @seltong, please, order the SLAResults by its status in alphabetical order.

Thank you in advance!

2021-05-27 12:41 UTC, rafaprax approved these changes

2021-05-27 15:58 UTC, seltong commented
Just started reviewing :)

2021-05-27 16:03 UTC, seltong commented
Just started reviewing :)

2021-05-27 17:15 UTC, rafaprax commented
ci:forward

2021-05-27 17:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-27 17:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/161/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/161/jenkins-report.html">here</a>.</b></p>

2021-05-27 17:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b">3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/5fa3d8a98430a12566d1c56bf33b46769e79c3a0">5fa3d8a98430a12566d1c56bf33b46769e79c3a0</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/161/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/161/jenkins-report.html">here</a>.</h5><pre><code>     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all artifacts for configuration 'classpath'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1276)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access\$1700(DefaultConfiguration.java:142)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1838)</code></pre></details></html>

2021-05-27 17:25 UTC, MarinhoFeliphe approved these changes

2021-05-27 17:42 UTC, MariMalta commented
ci:forward

2021-05-27 17:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-27 17:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/171/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/171/jenkins-report.html">here</a>.</b></p>

2021-05-27 17:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/161/">test-portal-source-format#161</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/161/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535958993">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-27[10:16:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/467/">publish-testray-report#467</a><br/></div></div>

2021-05-27 17:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b">3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/9bae66b33f1a0a3d57d7ec74c68b96c94bd27c30">9bae66b33f1a0a3d57d7ec74c68b96c94bd27c30</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/171/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/171/jenkins-report.html">here</a>.</h5><pre><code>     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] 
     [exec] Gradle build finished at 2021-05-27 17:49:49.004.
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all artifacts for configuration 'classpath'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1276)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access\$1700(DefaultConfiguration.java:142)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1838)</code></pre></details></html>

2021-05-27 17:57 UTC, MariMalta commented
ci:forward

2021-05-27 17:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-27 17:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/176/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">here</a>.</b></p>

2021-05-27 18:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b">3c08bd44a04fd98ad6b21c5365e39ffa8801cb3b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/178a884a33963895aac9b84264f7aeaa3eb0aaf3">178a884a33963895aac9b84264f7aeaa3eb0aaf3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/176/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">here</a>.</h5><pre><code>     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] Gradle build finished at 2021-05-27 18:04:36.739.
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all artifacts for configuration 'classpath'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1276)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access\$1700(DefaultConfiguration.java:142)</code></pre></details></html>

2021-05-27 18:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/171/">test-portal-source-format#171</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/171/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535959692">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-27[10:42:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/481/">publish-testray-report#481</a><br/></div></div>

2021-05-27 18:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/176/">test-portal-source-format#176</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535959777">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-27[10:57:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/485/">publish-testray-report#485</a><br/></div></div>

2021-05-27 22:10 UTC, MarinhoFeliphe commented
ci:test:sf

2021-05-27 22:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/579/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/579/jenkins-report.html">here</a>.</b></p>

2021-05-27 22:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4072ba2358536f35fd2f52ffcff4d3377519c591">4072ba2358536f35fd2f52ffcff4d3377519c591</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MariMalta/liferay-portal/tree/LPS-132726">LPS-132726</a><br/>Branch GIT ID: <a href="https://github.com/MariMalta/liferay-portal/commit/178a884a33963895aac9b84264f7aeaa3eb0aaf3">178a884a33963895aac9b84264f7aeaa3eb0aaf3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/579/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/579/jenkins-report.html">here</a>.</h5></details></html>

2021-05-27 22:15 UTC, MarinhoFeliphe commented
ci:forward

2021-05-27 22:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-27 22:15 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2021-05-27 22:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/579/">test-portal-source-format#579</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/579/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535999147">[master] ci:test:sf - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-27[15:12:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/1115/">publish-testray-report#1115</a><br/></div></div>

2021-05-28 00:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8416/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8416/jenkins-report.html">here</a>.</b></p>

2021-05-28 02:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 22 out of 24 jobs passed in 2 hours 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4072ba2358536f35fd2f52ffcff4d3377519c591">4072ba2358536f35fd2f52ffcff4d3377519c591</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4072ba2358536f35fd2f52ffcff4d3377519c591">4072ba2358536f35fd2f52ffcff4d3377519c591</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1914">Acceptance Upstream DXP (master) #1914</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435657/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328524/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328525/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/386883/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/388177/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435660/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11395/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11394/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/498157/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 24 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8416/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11396/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331160/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/498158/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/386882/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435657/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/388178/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/463396/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/359135/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328524/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328525/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/498159/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331159/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/386881/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/386883/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331158/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435659/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/388177/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435658/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435660/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11395/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11394/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435656/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/498157/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8416/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 4072ba [...]

2021-05-28 02:56 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8416//consoleFull)

2021-05-28 02:57 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102454
[Console](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8416//consoleFull)

2021-05-28 02:57 UTC, closed without merging

2021-05-28 03:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8416/">test-portal-acceptance-pullrequest(master)#8416</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8416/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/380">liferay-workflow#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1536084405">[master] ci:test:relevant - MariMalta &gt; liferay-workflow - PR#380 - 2021-05-27[17:14:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/985/">publish-testray-report#985</a><br/></div></div>