LPS-138925 Semver
liferay-workflow/liferay-portal pull request #646
Opened 2021-12-06 16:57 UTC by seltong

2021-12-06 16:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-12-06 17:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/730/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/730/jenkins-report.html">here</a>.</b></p>

2021-12-06 17:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/730/">test-portal-source-format#730</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/730/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/646">liferay-workflow#646</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1588085490">[master] ci:test:sf - seltong &gt; liferay-workflow - PR#646 - 2021-12-06[08:58:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/2437/">publish-testray-report#2437</a><br/></div></div>

2021-12-06 18:12 UTC, MarinhoFeliphe requested changes

2021-12-06 18:12 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-metrics-integration/src/main/java/com/liferay/portal/workflow/kaleo/metrics/integration/internal/helper/IndexerHelper.java
> +			_getNodeId(kaleoTransition.getSourceKaleoNodeId())
Hi @seltong,

Create another sourceNodeId method which a UnsafeSupplier as parameter.

2021-12-06 18:20 UTC, MarinhoFeliphe requested changes

2021-12-06 18:20 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-service/src/main/java/com/liferay/portal/workflow/metrics/internal/search/index/TransitionWorkflowMetricsIndexerImpl.java
> +		AddTransitionRequest.Builder builder =
@seltong, please rename this to addTransitionRequestBuilder.

thanks!

2021-12-07 22:00 UTC, MarinhoFeliphe requested changes

2021-12-07 22:00 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-service/src/main/java/com/liferay/portal/workflow/metrics/internal/search/index/TransitionWorkflowMetricsIndexerImpl.java
> +		);
Hi @seltong, 

put this block inline, like this `addDocument(...).build())`

2021-12-07 22:00 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-metrics-integration/src/main/java/com/liferay/portal/workflow/kaleo/metrics/integration/internal/helper/IndexerHelper.java
> +		DeleteTransitionRequest.Builder builder =
@seltong, rename this variable to deleteTransitionRequestBuilder.

2021-12-07 22:00 UTC, MarinhoFeliphe commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-api/src/main/java/com/liferay/portal/workflow/metrics/search/index/TransitionWorkflowMetricsIndexer.java
> +	public void deleteTransition(
@seltong, move this change to the creational commit.

2021-12-09 15:25 UTC, rafaprax commented
ci:test:sf

2021-12-09 15:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/263/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/263/jenkins-report.html">here</a>.</b></p>

2021-12-09 15:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/seltong/liferay-portal/tree/LPS-138925">LPS-138925</a><br/>Branch GIT ID: <a href="https://github.com/seltong/liferay-portal/commit/12c0a925a0de0fe4c1ee75f72576d06654f0baf0">12c0a925a0de0fe4c1ee75f72576d06654f0baf0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/263/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/263/jenkins-report.html">here</a>.</h5></details></html>

2021-12-09 15:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/263/">test-portal-source-format#263</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/263/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/646">liferay-workflow#646</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1588920085">[master] ci:test:sf - seltong &gt; liferay-workflow - PR#646 - 2021-12-09[07:26:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/1001/">publish-testray-report#1001</a><br/></div></div>

2021-12-09 18:06 UTC, MarinhoFeliphe approved these changes

2021-12-09 18:07 UTC, MarinhoFeliphe commented
ci:forward

2021-12-09 18:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-09 18:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2021-12-09 18:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1493/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1493/jenkins-report.html">here</a>.</b></p>

2021-12-09 20:00 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1493//consoleFull)

2021-12-09 20:00 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110939
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1493//consoleFull)

2021-12-09 20:00 UTC, closed without merging

2021-12-09 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1493/">test-portal-acceptance-pullrequest(master)#1493</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1493/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/646">liferay-workflow#646</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1589019234">[master] ci:test:relevant - seltong &gt; liferay-workflow - PR#646 - 2021-12-09[10:11:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/4661/">publish-testray-report#4661</a><br/></div></div>