LPS-142863 Create ResourceActions assignment section component
liferay-workflow/liferay-portal pull request #704
Opened 2022-01-06 23:15 UTC by jotascript

2022-01-06 23:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-01-06 23:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/883/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/883/jenkins-report.html">here</a>.</b></p>

2022-01-06 23:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/309954b089afafa8116ff2755079b09aaf965087">309954b089afafa8116ff2755079b09aaf965087</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jotascript/liferay-portal/tree/LPS-142863">LPS-142863</a><br/>Branch GIT ID: <a href="https://github.com/jotascript/liferay-portal/commit/42f1867c35aa513caf43b9cec526385e08e0fc91">42f1867c35aa513caf43b9cec526385e08e0fc91</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/883/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/883/jenkins-report.html">here</a>.</h5></details></html>

2022-01-06 23:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/883/">test-portal-source-format#883</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/883/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/704">liferay-workflow#704</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1597108563">[master] ci:test:sf - jotascript &gt; liferay-workflow - PR#704 - 2022-01-06[15:15:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/2274/">publish-testray-report#2274</a><br/></div></div>

2022-01-07 16:40 UTC, ramonmsp requested changes

2022-01-07 16:40 UTC, ramonmsp commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/EdgeInformation.js
> +					onChange={({target}) => {
@jotascript Is this too much code to onChange? What do you think about change it for two functions, one to set errors and another to set the selected item?

2022-01-07 16:40 UTC, ramonmsp commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/EdgeInformation.js
> +					onChange={({target}) => {
@jotascript Almost the same here!

2022-01-07 16:40 UTC, ramonmsp commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/NodeInformation.js
> +					onChange={({target}) => {
@jotascript Same here

2022-01-07 16:40 UTC, ramonmsp commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/NodeInformation.js
> +					onChange={({target}) => {
@jotascript Same here

2022-01-10 18:54 UTC, cgmonte commented
Just started reviewing :)

2022-01-12 19:38 UTC, closed without merging

2022-01-12 19:38 UTC, cgmonte commented
resent here: https://github.com/liferay-workflow/liferay-portal/pull/715