LPS-145404 Check if transition default exists to set the defaultEdge
liferay-workflow/liferay-portal pull request #740
Opened 2022-01-27 23:17 UTC by alinedoleron

- LPS-145977 search-experiences-web: Fix "User's Language" option for field name input
- LRQA-72793 Investigate CI failure of ImageField#UploadImageFromDocumentsAndMedia
- LPS-145418,LPS-145417,LPS-144110,LPS-144853,LPS-145419,LPS-145065,LPS-145421,LPS-145420,LPS-145505,LPS-145504 Fix Objects quarantined tests
- LPS-139040 Fix Objects Poshi tests
- COMMERCE-7950 Add path to Display Page Item Remove
- COMMERCE-7950 Add macro to remove Product Display Page
- COMMERCE-7950 Add test to verify user selects, changes and removes a Default Product Display page by navigating to channels page
- LPS-145215 Update language keys
- LPS-145215 buildLang
- LPS-145215 Update poshi tests
- LPS-105380 Sort ThemeDisplay.set* calls
- LPS-105380 Auto SF
- LPS-139938 Auto SF
- LPS-144839 SF, add an empty line, as we finished referencing variable 'serviceContext'
- LPS-145984 Add loading indicator to the add site modal
- LPS-145784 Don't add friendly url entry when on staging
- LPS-145784 Update mapping for both new and existing friendly URLs
- LPS-145567 Pass disabled to react and allow render when is disabled
- LPS-145567 Add MutationObserver to suscribe on input disabled attribute changes
- LPS-145567 Baseline
- artifact:ignore commerce-tax-engine-fixed-service 4.0.14 prep next
- artifact:ignore frontend-data-set-web 1.0.11 prep next
- artifact:ignore search-experiences-rest-api 1.0.2 prep next
- artifact:ignore search-experiences-service 1.0.2 prep next
- LPS-141823 Add CanSubmitEntryWithDoubleFieldBlank test
- LPS-139768 Change macro name to addLanguageOnPicklistItem
- LPS-139768 Add CanSetDifferentPicklistNameLanguage test
- LPS-145832 Fix test for JournalArticles w/ multiple translations
- LPS-145832 Fix test JournalArticleMultiLanguageSearchGroupIdsTest.testSearchEverything
- LPS-144442 SF, rename variable names
- LPS-144442 SF, rename variable names
- LPS-144442 SF, rename variable names
- LPS-144442 Auto SF
- LPS-144442 SF, rename variable names
- LPS-144442 Auto SF
- LPS-144442 SF, rename variable names
- LPS-144442 SF, rename variable names
- LPS-144442 SF, rename variable names
- LPS-144442 Auto SF
- LPS-144915 Add CP 2.0 Properties for Poshi Tests
- LPS-144915 SF
- LPS-144915 Add setUp for CP 2.0
- LPS-144915 SF
- LPS-144915 Add path, macro and testcase stub
- LPS-144915 SF
- LPS-144915 Fix TearDown
- LPS-144915 SF
- LPS-144915 Fix CP macro
- LPS-144915 Fix setup and teardown in testcase
- LPS-144732 Fix order: we will sort the assert statement by the expected parameter
- LPS-144732 SF
- LPS-145716 Add CanCreateAction test
- LPS-145897 Calculate formattedDate correctly for all translations
- LPS-144473 Move pencil icon to USERS for consistency
- LPS-144473 Add method to mark entries are not relevant in order to not show the Control Menu if there is not at least one relevant entry
- LPS-144473 Baseline
- LPS-144473 Make use of the new method
- LPS-144473 Mark the Layout Header as not relevant
- LPS-144473 Mark as relevant when in edit mode
- LPS-144473 Add SF exception to be able to pass HttpServletRequest as parameter
- LPS-144473 Update case
- LPS-145931 Update the config file name
- LPS-145941 Add property to skip instance
- LPS-145938 Fix typo
- LPS-145935 Modify macro to make it reusable
- LPS-145935 Update usage
- LPS-145934 Update parameter name
- LPS-145942 Add missing step
- LPS-145656 Change object schema to improve integration for Setup DXP Cloud Environment
- LPS-145656 Open Setup DXP Cloud throught the modal in ActivationStatus Page
- LPS-145656 SF
- LPS-145165 Change behavior to save select input in DXP Cloud Form
- LPS-145165 Remove product title to DXP and DXP Cloud request
- LPS-145165  Fix role validations to redirect pages
- LPS-145165  Fix icon to commerce_icon.svg
- LPS-145165 SF
- LPS-145656 upload
- LPS-145621 Add course display pages to Masterclass main navigation
- LPS-145621 Adds missing assignment
- LPS-145930 Modify case to use Search template
- LPS-145932 Fix typo
- LPS-144234 Poshi Automation for Bug LPS-142166
- LPS-144234 Migrate case to ContentDisplay
- LPS-144234 Modify descriptions and task messages
- LPS-141756 Poshi Automation for Bug LPS-137055
- LPS-141756 Modify description
- LPS-141756 Rename case
- LPS-141756 Modify task messages
- LPS-141756 Use assertElementNotPresent
- LPS-141756 Auto SF
- LPS-142866 Add Role component references to SelectAssignment.js
- LPS-142866 Create Role assignment type component
- Revert "LPS-135604 Creating unit test to verify if numeric predefined value persists"
- Revert "LPS-135604 Synchronizing text field value"
- Revert "LPS-135604 Update field affected by calculate rule using predefined value"
- Revert "LPS-135604 Setting predefined value in the field update"
- Revert "LPS-135604 Updating correctly field affected by calculate rule"
- Revert "LPS-135604 Setting localizedValue from the current field"
- Revert "LPS-145842 Fix the confirmation dialog when deleting an object entry"
- LPS-145842 Fix confirmation dialog, while preserving forward of the entire `action` object to dropdown item click callback
- COMMERCE-8099 - Reordering a product with options causes mini-cart error
- COMMERCE-7905 add dependency with account-api
- COMMERCE-7905 fixed the find of the billing address
- COMMERCE-7905 fixed the find of the shipping address
- COMMERCE-8198 Fix order type rel condition
- LPS-145893 Migrate FDS displays in `remote-app-web`
- LPS-145893 Like this
- LPS-143303 Separate logic in two methods. The first one creates the empty layouts (just the entities), and the second populates them with data. This way we can reference the layouts in the data, such as link to pages and other logic
- LPS-143303 SF
- COMMERCE-8262 make requested delivery date optional
- LPS-145659 When displaying the summary of a process, make it possible to get the selected Layout IDs not just for a local staging process, but a remote one as well.
- LPS-145659 Use the languageId to query the parent page's name. Otherwise, we just get the whole XML containing the page name in every translation.
- LPS-145731 Remove ObjectForms#FormWithInactivatedObjectCannotBeUsed test
- LPS-139768 Change additional instance of previously changed macro
- LRAC-7890 Remove bug ticket message
- LRAC-8176 [Remove] ViewAllDocumentsAndMediaShownInAssetList from quarantine
- LRAC-10452 Add while loop in blockCustomEvent macro to search the event
- LRAC-10452 Add while loop in unblockCustomEvent macro to search the event
- LRAC-10452 Add while loop in unhideEvent macro to search the event
- LRAC-10450 Fix setUp adding lauchDXP macro that was missing
- LRAC-10450 Fix CanChangeRetentionPeriod with launchAC macro that was missing
- LRAC-10451 Change the attribute name to one that is not present in another test
- LRAC-10451 Change the edit option
- LRAC-8176 - [Add] tests to quarantine
- LRAC-10434 - [Disable] test
- LPS-140729 Change ObjectPortlet#StringDisplayedOnAutoGeneratedTable test to add the limit of characters
- LPS-145352 Improve CreateObject#RelationshipTabReappearsWhenReactivatedManyToMany test
- LRCI-2566 Change default browser Testray value to Chrome 86
- LPS-145945 Fix WebContentDisplayPortlet.viewContent failure after LPS-130552
- LPS-145969 Update Web Content description translation
- LPS-145965 Use suitable xpath
- LRQA-72775 Include Language Override tests in ci:test:usm
- LPS-145772 Create MobileContainer to wrap content
- LPS-145772 Move steps and selectedStep to context
- LPS-145772 Use steps from context
- LPS-145772 Rewrite logic for FormActions to handle mobile and large screen
- LPS-145772 Use MobileContainer for basics form
- LPS-145772 SF
- LPS-145772 Force Validation when the page loads with MobileContainer
- LPS-145772 Use Variables
- LPS-145772 upload
- LRQA-72567 Add permissions test for page tree
- LPS-144642 Update transitions references when changing a node id
- COMMERCE-8133 account-api added new action key for addresses
- COMMERCE-8133 account-service added support to new addresses actions
- COMMERCE-8133 commerce-ac [...]

2022-01-27 23:17 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-01-27 23:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1230/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1230/jenkins-report.html">here</a>.</b></p>

2022-01-27 23:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-145404">LPS-145404</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/8b2260fe30c01a5016afc7e8f37427e60b2705be">8b2260fe30c01a5016afc7e8f37427e60b2705be</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1230/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1230/jenkins-report.html">here</a>.</h5></details></html>

2022-01-27 23:22 UTC, alinedoleron commented
ci:test:relevant

2022-01-27 23:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/68/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/68/jenkins-report.html">here</a>.</b></p>

2022-01-27 23:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1230/">test-portal-source-format#1230</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1230/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604848951">[master] ci:test:sf - alinedoleron &gt; liferay-workflow - PR#740 - 2022-01-27[15:17:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/4196/">publish-testray-report#4196</a><br/></div></div>

2022-01-28 01:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 22 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 26 out of 28 jobs passed in 1 hour 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2862">Acceptance Upstream DXP (master) #2862</a></p><details><summary><strong>ci:test:stable - 22 out of 24 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/659/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/652/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25644/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29763/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369366/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28816/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29765/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/447223/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25646/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29767/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483242/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/655/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/27295/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8655/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/653/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25645/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28817/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30621/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28815/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25643/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/447221/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25642/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29764/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/654/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 25 out of 28 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/68/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/659/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/652/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25644/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29763/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369366/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28816/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29765/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/447223/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25646/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29767/">test-portal-acceptance-pullrequest-ba [...]

2022-01-28 01:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/68/">test-portal-acceptance-pullrequest(master)#68</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/68/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604870280">[master] ci:test:relevant - alinedoleron &gt; liferay-workflow - PR#740 - 2022-01-27[15:34:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/118/">publish-testray-report#118</a><br/></div></div>

2022-01-28 19:01 UTC, naraandrade requested changes
Check if there's already a transition with defaultEdge == true in the transition's source node

2022-02-01 20:46 UTC, alinedoleron commented
ci:test:sf

2022-02-01 20:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/1466/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1466/jenkins-report.html">here</a>.</b></p>

2022-02-01 20:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9b0dee253287fb23e10736f989d56872ef29f14">b9b0dee253287fb23e10736f989d56872ef29f14</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-145404">LPS-145404</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/3b9b717a5df00ac1ff43d9513100d621e0633a29">3b9b717a5df00ac1ff43d9513100d621e0633a29</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1466/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1466/jenkins-report.html">here</a>.</h5></details></html>

2022-02-01 20:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1466/">test-portal-source-format#1466</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1466/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1606112747">[master] ci:test:sf - alinedoleron &gt; liferay-workflow - PR#740 - 2022-02-01[12:46:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/5126/">publish-testray-report#5126</a><br/></div></div>

2022-02-02 14:07 UTC, alinedoleron commented
> Check if there's already a transition with defaultEdge == true in the transition's source node

Hi @naraandrade, I've made the changes.

2022-02-02 15:35 UTC, naraandrade requested changes
Update

2022-02-02 15:35 UTC, naraandrade commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/source-builder/deserializeUtil.js
> +								defaultEdge:
Update condition

2022-02-02 16:17 UTC, alinedoleron commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/source-builder/deserializeUtil.js
> +								defaultEdge:
Thank you, Nara! I've made the changes.

2022-02-02 16:17 UTC, alinedoleron commented
ci:test:sf

2022-02-02 16:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1487/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1487/jenkins-report.html">here</a>.</b></p>

2022-02-02 16:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9b0dee253287fb23e10736f989d56872ef29f14">b9b0dee253287fb23e10736f989d56872ef29f14</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-145404">LPS-145404</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/1394392856831d55d763f6900fd722f1bddbbbd5">1394392856831d55d763f6900fd722f1bddbbbd5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1487/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1487/jenkins-report.html">here</a>.</h5></details></html>

2022-02-02 16:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1487/">test-portal-source-format#1487</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1487/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1606475387">[master] ci:test:sf - alinedoleron &gt; liferay-workflow - PR#740 - 2022-02-02[08:18:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/4820/">publish-testray-report#4820</a><br/></div></div>

2022-02-02 17:41 UTC, naraandrade commented
ci:forward

2022-02-02 17:41 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-02-02 17:41 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-02-02 17:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/789/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/789/jenkins-report.html">here</a>.</b></p>

2022-02-02 19:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/789/">test-portal-acceptance-pullrequest(master)#789</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/789/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1606634088">[master] ci:test:relevant - alinedoleron &gt; liferay-workflow - PR#740 - 2022-02-02[09:41:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/2437/">publish-testray-report#2437</a><br/></div></div>

2022-02-02 19:52 UTC, naraandrade commented
ci:test:relevant

2022-02-02 19:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/1634/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1634/jenkins-report.html">here</a>.</b></p>

2022-02-02 22:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 21 out of 25 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 24 out of 28 jobs passed in 2 hours 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9b0dee253287fb23e10736f989d56872ef29f14">b9b0dee253287fb23e10736f989d56872ef29f14</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9b0dee253287fb23e10736f989d56872ef29f14">b9b0dee253287fb23e10736f989d56872ef29f14</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2877">Acceptance Upstream DXP (master) #2877</a></p><details><summary><strong>ci:test:stable - 21 out of 25 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1582/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26560/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1574/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1575/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399933/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26336/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483514/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337360/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1573/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30749/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482770/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475686/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9448/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15239/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26337/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26559/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399934/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337358/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17397/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/349818/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1576/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475685/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399932/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475684/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399935/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/1634/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1582/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26560/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1574/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1575/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399933/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26336/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483514/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337360/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li>< [...]

2022-02-02 22:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/1634/">test-portal-acceptance-pullrequest(master)#1634</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1634/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-workflow/liferay-portal/pull/740">liferay-workflow#740</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1606699523">[master] ci:test:relevant - alinedoleron &gt; liferay-workflow - PR#740 - 2022-02-02[11:52:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/4837/">publish-testray-report#4837</a><br/></div></div>

2022-02-02 23:39 UTC, naraandrade commented
ci:forward

2022-02-02 23:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-02-02 23:39 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-02-02 23:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/242//consoleFull)

2022-02-02 23:40 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/112992
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/242//consoleFull)

2022-02-02 23:40 UTC, closed without merging